import { defUnit } from "./helpers";

export const allPossibleIngredients = [
  "Almonds",
  "Almond flour",
  "All-purpose flour",
  "Apples",
  "Asparagus",
  "Avocado",
  "Bacon",
  "Baking powder",
  "Baking soda",
  "Banana",
  "Barley",
  "Bread flour",
  "Brown butter",
  "Buttermilk",
  "Cake flour",
  "Candied ginger",
  "Cocoa nibs",
  "Corn syrup",
  "Dark chocolate",
  "Gelatin",
  "Heavy cream",
  "Lemon zest",
  "Marzipan",
  "Molasses",
  "Pecan flour",
  "Powdered sugar",
  "Raisins",
  "Shortening",
  "Sour cream",
  "Condensed milk",
  "Vanilla bean",
  "Vanilla sugar",
  "White chocolate",
  "Whole wheat flour",
  "Yogurt",
  "Basil",
  "Bay leaves",
  "Beans",
  "Beets",
  "Black pepper",
  "Blueberries",
  "Bread crumbs",
  "Broccoli",
  "Brown sugar",
  "Brussels sprouts",
  "Butter",
  "Cabbage",
  "Carrots",
  "Cauliflower",
  "Celery",
  "Cheddar cheese",
  "Mozzarella cheese",
  "Cherries",
  "Chicken breasts",
  "Chicken broth",
  "Chili powder",
  "Cilantro",
  "Cinnamon",
  "Cloves",
  "Cocoa powder",
  "Coconut milk",
  "Coconut oil",
  "Cornmeal",
  "Cornstarch",
  "Cream cheese",
  "Cream of mushroom soup",
  "Cranberries",
  "Cumin",
  "Dill",
  "Eggs",
  "Fennel",
  "Fish sauce",
  "Garlic",
  "Ginger",
  "Grapes",
  "Green beans",
  "Ground beef",
  "Ham",
  "Honey",
  "Hot sauce",
  "Kale",
  "Ketchup",
  "Leek",
  "Lemon juice",
  "Lentils",
  "Lime",
  "Maple syrup",
  "Mayonnaise",
  "Milk",
  "Mushrooms",
  "Mustard",
  "Nutmeg",
  "Olive oil",
  "Onion",
  "Oregano",
  "Orange",
  "Paprika",
  "Parmesan cheese",
  "Parsley",
  "Pasta",
  "Peas",
  "Pecans",
  "Pineapple",
  "Pork chop",
  "Potatoes",
  "Raspberries",
  "Red Bell Pepper",
  "Red pepper flakes",
  "Rice",
  "Rosemary",
  "Salmon",
  "Salt",
  "Sausage",
  "Soy sauce",
  "Spinach",
  "Sugar",
  "Thyme",
  "Tomato paste",
  "Tomato sauce",
  "Turkey",
  "Vanilla extract",
  "Vegetable oil",
  "Vinegar",
  "Yeast",
  "Yellow Bell Pepper",
  "Zucchini",
];

export const commonUnits = [
  "mg",
  "g",
  "kg",
  "ml",
  "l",
  "pinch",
  "quart",
  "pint",
  "lbs",
  "oz",
  "tsp",
  "tbsp",
  "cup",
];

export const extraUnits = [
  defUnit,
  "gallon",
  "piece",
  "slice",
  "strip",
  "drop",
  "dash",
  "smidgen",
  "bunch",
  "can",
  "jar",
  "stick",
  "clove",
  "head",
  "fillet",
  "block",
  "sheet",
  "pack",
  "packet",
  "bag",
  "bar",
  "cube",
  "handful",
  "bottle",
  "sprig",
  "stalk",
  "ear",
  "bowl",
  "scoop",
  "dozen",
  "whole",
];

export const allPossibleChefActions = [
  { actionName: "Bake", time: 20, unit: "min", equipment: "oven" },
  { actionName: "Boil", time: 5, unit: "min", equipment: "stove" },
  { actionName: "Simmer", time: 30, unit: "min", equipment: "stove" },
  { actionName: "Fry", time: 5, unit: "min", equipment: "stove" },
  { actionName: "Sauté", time: 5, unit: "min", equipment: "stove" },
  { actionName: "Steam", time: 10, unit: "min", equipment: "steamer" },
  { actionName: "Grill", time: 20, unit: "min", equipment: "grill" },
  { actionName: "Roast", time: 20, unit: "min", equipment: "oven" },
  { actionName: "Broil", time: 20, unit: "min", equipment: "broiler" },
  { actionName: "Poach", time: 8, unit: "min", equipment: "stove" },
  { actionName: "Blanch", time: 1, unit: "min", equipment: "stove" },
  { actionName: "Sear", time: 2, unit: "min", equipment: "stove" },
  { actionName: "Braise", time: 10, unit: "min", equipment: "oven" },
  { actionName: "Stew", time: 45, unit: "min", equipment: "slow cooker" },
  { actionName: "Toast", time: 2, unit: "min", equipment: "toaster" },
  { actionName: "Smoke", time: 2, unit: "hours", equipment: "smoker" },
  { actionName: "Cure", time: 5, unit: "hours", equipment: "refrigerator" },
  { actionName: "Ferment", time: 24, unit: "hours", equipment: "refrigerator" },
  { actionName: "Marinate", time: 8, unit: "hours", equipment: "refrigerator" },
  { actionName: "Slice", time: 0, unit: "min", equipment: "knife" },
  { actionName: "Dice", time: 0, unit: "min", equipment: "knife" },
  { actionName: "Chop", time: 0, unit: "min", equipment: "knife" },
  { actionName: "Mince", time: 0, unit: "min", equipment: "knife" },
  { actionName: "Grate", time: 0, unit: "min", equipment: "grater" },
  { actionName: "Shred", time: 0, unit: "min", equipment: "grater" },
  { actionName: "Peel", time: 0, unit: "min", equipment: "peeler" },
  { actionName: "Trim", time: 0, unit: "min", equipment: "knife" },
  { actionName: "Core", time: 0, unit: "min", equipment: "corer" },
  { actionName: "Score", time: 0, unit: "min", equipment: "knife" },
  { actionName: "Knead", time: 10, unit: "min", equipment: "stand mixer" },
  { actionName: "Whisk", time: 5, unit: "min", equipment: "hand mixer" },
  { actionName: "Mix", time: 0, unit: "min", equipment: "bowl" },
  { actionName: "Fold", time: 0, unit: "min", equipment: "spatula" },
  { actionName: "Blend", time: 0, unit: "min", equipment: "blender" },
  { actionName: "Purée", time: 0, unit: "min", equipment: "food processor" },
  { actionName: "Sieve", time: 0, unit: "min", equipment: "sieve" },
  { actionName: "Strain", time: 0, unit: "min", equipment: "strainer" },
  { actionName: "Garnish", time: 0, unit: "min", equipment: "none" },
  { actionName: "Dress", time: 0, unit: "min", equipment: "none" },
  { actionName: "Emulsify", time: 0, unit: "min", equipment: "blender" },
  { actionName: "Season", time: 0, unit: "min", equipment: "none" },
  { actionName: "Glaze", time: 0, unit: "min", equipment: "brush" },
  { actionName: "Infuse", time: 0, unit: "min", equipment: "stove" },
];
