import { defUnit } from "./helpers";

export const allPossibleIngredients = [
  "All-purpose flour",
  "Almond flour",
  "Apples",
  "Asparagus",
  "Avocado",
  "Bacon",
  "Baguette",
  "Baking powder",
  "Baking soda",
  "Banana",
  "Barley",
  "Basil",
  "Bay leaves",
  "Beans",
  "Beets",
  "Black pepper",
  "Blueberries",
  "Bread",
  "Bread buns",
  "Bread crumbs",
  "Bread flour",
  "Broccoli",
  "Brown butter",
  "Brown rice",
  "Brown sugar",
  "Brussels sprouts",
  "Butter",
  "Buttermilk",
  "Cabbage",
  "Cake flour",
  "Candied ginger",
  "Carrots",
  "Cauliflower",
  "Celery",
  "Cheddar cheese",
  "Cherries",
  "Chia seeds",
  "Chicken breasts",
  "Chicken broth",
  "Chili powder",
  "Cilantro",
  "Cinnamon",
  "Cloves",
  "Cocoa nibs",
  "Cocoa powder",
  "Coconut milk",
  "Coconut oil",
  "Condensed milk",
  "Cornmeal",
  "Cornstarch",
  "Corn syrup",
  "Couscous",
  "Cranberries",
  "Cream cheese",
  "Cream of mushroom soup",
  "Cumin",
  "Dark chocolate",
  "Dill",
  "Eggs",
  "Fennel",
  "Feta cheese",
  "Fish sauce",
  "Garlic",
  "Gelatin",
  "Ginger",
  "Grapes",
  "Graham crackers",
  "Greek yogurt",
  "Green beans",
  "Ground beef",
  "Ham",
  "Heavy cream",
  "Honey",
  "Hot sauce",
  "Kale",
  "Ketchup",
  "Leek",
  "Lemon",
  "Lemon juice",
  "Lemon zest",
  "Lentils",
  "Lime",
  "Macadamia nuts",
  "Maple syrup",
  "Marzipan",
  "Mayonnaise",
  "Milk",
  "Molasses",
  "Mozzarella cheese",
  "Mushrooms",
  "Mustard",
  "Nutmeg",
  "Oats",
  "Olive oil",
  "Onion",
  "Orange",
  "Oregano",
  "Paprika",
  "Parmesan cheese",
  "Parsley",
  "Pasta",
  "Peas",
  "Pecan flour",
  "Pecans",
  "Pecorino cheese",
  "Pineapple",
  "Pine nuts",
  "Poppy seeds",
  "Pork chop",
  "Potatoes",
  "Powdered sugar",
  "Quinoa",
  "Raisins",
  "Raspberries",
  "Red Bell Pepper",
  "Red pepper flakes",
  "Rice",
  "Ricotta cheese",
  "Rosemary",
  "Salmon",
  "Salt",
  "Sausage",
  "Seasoning",
  "Shortening",
  "Sliced bread",
  "Sour cream",
  "Soy sauce",
  "Spinach",
  "Sugar",
  "Swiss cheese",
  "Thyme",
  "Tomato paste",
  "Tomato sauce",
  "Turkey",
  "Vanilla bean",
  "Vanilla extract",
  "Vanilla sugar",
  "Vegetable oil",
  "Vinegar",
  "Water",
  "Walnuts",
  "White chocolate",
  "Whole wheat flour",
  "Yeast",
  "Yellow Bell Pepper",
  "Yogurt",
  "Zucchini",
];

export const commonUnits = [
  "mg",
  "g",
  "kg",
  "ml",
  "liter",
  "whole",
  "quart",
  "pint",
  "lbs",
  "oz",
  "tsp",
  "tbsp",
  "cup",
  "can",
];

export const extraUnits = [
  defUnit,
  "gallon",
  "piece",
  "slice",
  "strip",
  "drop",
  "dash",
  "smidgen",
  "bunch",
  "jar",
  "stick",
  "clove",
  "head",
  "fillet",
  "block",
  "sheet",
  "pack",
  "packet",
  "bag",
  "bar",
  "cube",
  "handful",
  "bottle",
  "sprig",
  "stalk",
  "ear",
  "bowl",
  "scoop",
  "dozen",
  "pinch",
];

export const allPossibleChefActions = [
  { actionName: "Bake", time: 20, unit: "min", equipment: "oven" },
  { actionName: "Boil", time: 5, unit: "min", equipment: "stove" },
  { actionName: "Fry", time: 5, unit: "min", equipment: "stove" },
  { actionName: "Steam", time: 10, unit: "min", equipment: "steamer" },
  { actionName: "Grill", time: 20, unit: "min", equipment: "grill" },
  { actionName: "Add", time: -1, unit: "min", equipment: "hand" },
  { actionName: "Slice", time: -1, unit: "min", equipment: "knife" },
  { actionName: "Dice", time: -1, unit: "min", equipment: "knife" },
  { actionName: "Chop", time: -1, unit: "min", equipment: "knife" },
  { actionName: "Peel", time: -1, unit: "min", equipment: "peeler" },
  { actionName: "Trim", time: -1, unit: "min", equipment: "knife" },
  { actionName: "Mix", time: -1, unit: "min", equipment: "bowl" },
  { actionName: "Simmer", time: 30, unit: "min", equipment: "stove" },
  { actionName: "Sauté", time: 5, unit: "min", equipment: "stove" },
  { actionName: "Roast", time: 20, unit: "min", equipment: "oven" },
  { actionName: "Broil", time: 20, unit: "min", equipment: "broiler" },
  { actionName: "Poach", time: 8, unit: "min", equipment: "stove" },
  { actionName: "Blanch", time: 1, unit: "min", equipment: "stove" },
  { actionName: "Sear", time: 2, unit: "min", equipment: "stove" },
  { actionName: "Braise", time: 10, unit: "min", equipment: "oven" },
  { actionName: "Stew", time: 45, unit: "min", equipment: "slow cooker" },
  { actionName: "Toast", time: 2, unit: "min", equipment: "toaster" },
  { actionName: "Smoke", time: 2, unit: "hours", equipment: "smoker" },
  { actionName: "Cure", time: 5, unit: "hours", equipment: "refrigerator" },
  { actionName: "Ferment", time: 24, unit: "hours", equipment: "refrigerator" },
  { actionName: "Marinate", time: 8, unit: "hours", equipment: "refrigerator" },
  { actionName: "Mince", time: -1, unit: "min", equipment: "knife" },
  { actionName: "Grate", time: -1, unit: "min", equipment: "grater" },
  { actionName: "Shred", time: -1, unit: "min", equipment: "grater" },
  { actionName: "Core", time: -1, unit: "min", equipment: "corer" },
  { actionName: "Score", time: -1, unit: "min", equipment: "knife" },
  { actionName: "Knead", time: 10, unit: "min", equipment: "stand mixer" },
  { actionName: "Whisk", time: 5, unit: "min", equipment: "hand mixer" },
  { actionName: "Fold", time: -1, unit: "min", equipment: "spatula" },
  { actionName: "Blend", time: -1, unit: "min", equipment: "blender" },
  { actionName: "Purée", time: -1, unit: "min", equipment: "food processor" },
  { actionName: "Sieve", time: -1, unit: "min", equipment: "sieve" },
  { actionName: "Strain", time: -1, unit: "min", equipment: "strainer" },
  { actionName: "Garnish", time: -1, unit: "min", equipment: "none" },
  { actionName: "Dress", time: -1, unit: "min", equipment: "none" },
  { actionName: "Emulsify", time: -1, unit: "min", equipment: "blender" },
  { actionName: "Season", time: -1, unit: "min", equipment: "none" },
  { actionName: "Glaze", time: -1, unit: "min", equipment: "brush" },
  { actionName: "Infuse", time: -1, unit: "min", equipment: "stove" },
];
